---
contact_links:
  - name: 💬 Discord Chat
    url: https://discord.gg/ykp5kb46TY
    about: >
      Ask questions and talk to other CHANGEME_NAME users and the maintainers.

  - name: 📧 Email
    url: https://mailxto.com/tz9wiglren
    about: Send me an email if you wanna say more or talk privately.
