[tool.poetry]
name = "repo"
version = "0.1.0"
description = ""
authors = ["Obscurely <adrian.obscurely@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pillow = "^10.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
