---
name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  CARGO_TERM_COLOR: always
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: "softprops/action-gh-release@v1"
        with:
          generate_release_notes: true
          name: ${{ github.event.repository.name }} ${{ github.ref_name }}
          prerelease: false
          body: "Explicit changelog comming soon!"
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencies
        run: |
          brew install create-dmg
          brew install grep
          brew install gnu-sed
          brew install gnu-tar
          brew install coreutils
      - name: Build
        run: cargo build --release
      - name: Prepare
        run: mkdir -p target/osx
      - name: Copy bin
        run: |
          BIN_NAME=$(ggrep -o -P '(?<=name = ").*(?=")' Cargo.toml)
          cp "target/release/$BIN_NAME" "target/osx/$BIN_NAME-macos"
      - name: Dotapp
        run: |
          BIN_NAME=$(ggrep -o -P '(?<=name = ").*(?=")' Cargo.toml)
          cp "target/osx/$BIN_NAME-macos" "resources/macos/${GITHUB_REPOSITORY##*/}.app/Contents/MacOS/$BIN_NAME"
          cd resources/macos/
          gsed -i "s/VERSION_PLACEHOLDER/${GITHUB_REF##*/}/g" "${GITHUB_REPOSITORY##*/}.app/Contents/Info.plist"
          gtar -czf "$BIN_NAME-macos-app.tar.gz" "${GITHUB_REPOSITORY##*/}.app/"
          cd ../../
          cp "resources/macos/$BIN_NAME-macos-app.tar.gz" "target/osx/$BIN_NAME-macos-app.tar.gz"
      - name: DMG installer
        run: |
          cd resources/macos
          ./make-dmg.sh
          cd ../../
      - name: Archive for Homebrew
        run: |
          BIN_NAME=$(ggrep -o -P '(?<=name = ").*(?=")' Cargo.toml)
          cp LICENSE target/osx/LICENSE
          cp README.md target/osx/README.md
          cd target/osx/
          cp "$BIN_NAME-macos" "$BIN_NAME"
          gtar -czf "$BIN_NAME-macos.tar.gz" "$BIN_NAME" LICENSE README.md
          rm -f README.md LICENSE "$BIN_NAME"
          cd ../../
      - name: Homebrew
        if: "contains(github.ref, 'stable')"
        run: |
          BIN_NAME=$(ggrep -o -P '(?<=name = ").*(?=")' Cargo.toml)
          PARSED_VERSION=$(echo "${GITHUB_REF##*/}" | ggrep -o -P '(?<=v).*(?=-)')
          cd target/osx/
          TAR_SHA=$(gsha256sum "$BIN_NAME-macos.tar.gz" | gsed "s/  $BIN_NAME-macos.tar.gz//g")
          cd ../../
          gsed -i "s/VERSION_PLACEHOLDER/$PARSED_VERSION/g" "resources/macos/$BIN_NAME.rb"
          gsed -i "s/SHA_PLACEHOLDER/$TAR_SHA/g" "resources/macos/$BIN_NAME.rb"
          git clone "https://github.com/$GITHUB_REPOSITORY_OWNER/homebrew-tap"
          mkdir -p homebrew-tap/Formula
          cp "resources/macos/$BIN_NAME.rb" "homebrew-tap/Formula/$BIN_NAME.rb"
      - name: Commit homebrew file
        if: "contains(github.ref, 'stable')"
        run: |
          cd homebrew-tap/
          git config --local user.name "$GITHUB_REPOSITORY_OWNER"
          git config --local user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
          git add .
          git commit -m "update ${GITHUB_REPOSITORY##*/}"
          git push "https://$GITHUB_REPOSITORY_OWNER:$API_TOKEN_GITHUB@github.com/$GITHUB_REPOSITORY_OWNER/homebrew-tap.git"
      - name: Upload assets
        uses: "softprops/action-gh-release@v1"
        with:
          files: |
            target/osx/*
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-pc-windows-msvc"
      - name: Install cargo-wix
        shell: bash
        run: cargo install cargo-wix
      - name: Build
        run: cargo build --release
      - name: Prepare
        shell: bash
        run: mkdir -p target/win
      - name: Copy bin
        shell: bash
        run: |
          BIN_NAME=$(LC_ALL=en_US.utf8 grep -o -P '(?<=name = ").*(?=")' Cargo.toml)
          cp "target/release/$BIN_NAME.exe" "target/win/$BIN_NAME-windows.exe"
      - name: Setup Wix
        shell: bash
        run: |
          mkdir wix
          cp "resources/windows/main.wxs" "wix/main.wxs"
          cp "resources/windows/License.rtf" "wix/License.rtf"
      - name: Run cargo wix
        shell: pwsh
        run: |
          cargo wix --nocapture
      - name: Copy setup
        shell: bash
        run: |
          BIN_NAME=$(LC_ALL=en_US.utf8 grep -o -P '(?<=name = ").*(?=")' Cargo.toml)
          VER=$(LC_ALL=en_US.utf8 grep -o -P '(?<=version = ").*(?=")' Cargo.toml | head -n 1)
          cp "target/wix/$BIN_NAME-$VER-x86_64.msi" "target/win/$BIN_NAME-windows-setup.msi"
      - name: Upload assets
        uses: "softprops/action-gh-release@v1"
        with:
          files: |
            target/win/*
